services:
  hakuyo:
    image: ghcr.io/airesearchlab/hakuyo-ros:humble
    environment:
      - LAUNCH_FILENAME=urg_node2_serial.launch.py
      - AUTO_START=true
      - NODE_NAME=urg_node2
      - SCAN_TOPIC_NAME=scan
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
